version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fabriclaunch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniosecret
    volumes:
      - minio_data:/data

  web:
    build:
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DRIZZLE_URL: postgres://postgres:postgres@postgres:5432/fabriclaunch
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/fabriclaunch
      NEXT_PUBLIC_EXTERNAL_URL: http://localhost:3000
      AUTH_URL: http://localhost:3000
      PASSWORD_SALT: ${PASSWORD_SALT}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: noreply@fabriclaunch.com
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: miniosecret
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_REGION: us-east-1
      MINIO_BUCKET_NAME: fabriclaunch
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
