// This file is auto-generated by @hey-api/openapi-ts

export const $main_AddressWithCerts = {
    type: 'object',
    properties: {
        address: {
            '$ref': '#/definitions/main.HostPort'
        },
        clientTLSCert: {
            type: 'string'
        },
        serverTLSCert: {
            type: 'string'
        }
    }
} as const;

export const $main_ChannelGenesisResponse = {
    type: 'object',
    properties: {
        channel: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const $main_ChannelUpdate = {
    type: 'object',
    properties: {
        content: {
            type: 'string'
        },
        id: {
            type: 'string'
        }
    }
} as const;

export const $main_CreateChannelInput = {
    type: 'object',
    properties: {
        consenters: {
            type: 'array',
            items: {
                '$ref': '#/definitions/main.AddressWithCerts'
            }
        },
        name: {
            type: 'string'
        },
        ordererOrgs: {
            type: 'array',
            items: {
                '$ref': '#/definitions/main.Organization'
            }
        },
        peerOrgs: {
            type: 'array',
            items: {
                '$ref': '#/definitions/main.Organization'
            }
        }
    }
} as const;

export const $main_DecodeBlockInput = {
    type: 'object',
    properties: {
        dataB64: {
            type: 'string'
        }
    }
} as const;

export const $main_DecodeBlockResponse = {
    type: 'object',
    properties: {
        data: {
            type: 'object',
            additionalProperties: {}
        }
    }
} as const;

export const $main_HostPort = {
    type: 'object',
    properties: {
        host: {
            type: 'string'
        },
        port: {
            type: 'integer'
        }
    }
} as const;

export const $main_Organization = {
    type: 'object',
    properties: {
        anchorPeers: {
            type: 'array',
            items: {
                '$ref': '#/definitions/main.HostPort'
            }
        },
        name: {
            type: 'string'
        },
        ordererEndpoints: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        signCACert: {
            type: 'string'
        },
        tlsCACert: {
            type: 'string'
        }
    }
} as const;

export const $main_Response = {
    type: 'object',
    additionalProperties: {}
} as const;

export const $main_SetAnchorPeersInput = {
    type: 'object',
    properties: {
        anchorPeers: {
            type: 'array',
            items: {
                '$ref': '#/definitions/main.HostPort'
            }
        },
        blockB64: {
            type: 'string'
        },
        channelName: {
            type: 'string'
        },
        mspID: {
            type: 'string'
        }
    }
} as const;

export const $main_SetAnchorPeersResponse = {
    type: 'object',
    properties: {
        blockB64: {
            type: 'string'
        },
        noChanges: {
            type: 'boolean'
        }
    }
} as const;