// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostApiBlockAnchorpeersData, PostApiBlockAnchorpeersResponse, PostApiBlockDecodeData, PostApiBlockDecodeResponse, PostApiChannelGenesisData, PostApiChannelGenesisResponse, PostApiChannelUpdateData, PostApiChannelUpdateResponse } from './types.gen';

/**
 * Set anchor peers to a config block
 * Set anchor peers to a config block
 * @param data The data for the request.
 * @param data.update Anchor Peers Info
 * @returns main_SetAnchorPeersResponse OK
 * @throws ApiError
 */
export const postApiBlockAnchorpeers = (data: PostApiBlockAnchorpeersData): CancelablePromise<PostApiBlockAnchorpeersResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/block/anchorpeers',
    body: data.update
}); };

/**
 * Decode a block
 * Decode a block from base64 to JSON
 * @param data The data for the request.
 * @param data.block Block Data
 * @returns main_DecodeBlockResponse OK
 * @throws ApiError
 */
export const postApiBlockDecode = (data: PostApiBlockDecodeData): CancelablePromise<PostApiBlockDecodeResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/block/decode',
    body: data.block
}); };

/**
 * Create a new channel genesis
 * Create a new channel with the given name and description
 * @param data The data for the request.
 * @param data.channel Channel Genesis Info
 * @returns main_ChannelGenesisResponse Created
 * @throws ApiError
 */
export const postApiChannelGenesis = (data: PostApiChannelGenesisData): CancelablePromise<PostApiChannelGenesisResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/channel/genesis',
    body: data.channel
}); };

/**
 * Create a channel update
 * Create an update for an existing channel
 * @param data The data for the request.
 * @param data.update Channel Update Info
 * @returns main_Response Created
 * @throws ApiError
 */
export const postApiChannelUpdate = (data: PostApiChannelUpdateData): CancelablePromise<PostApiChannelUpdateResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/channel/update',
    body: data.update,
    errors: {
        400: 'Bad Request'
    }
}); };