// This file is auto-generated by @hey-api/openapi-ts

export type main_AddressWithCerts = {
    address?: main_HostPort;
    clientTLSCert?: string;
    serverTLSCert?: string;
};

export type main_ChannelGenesisResponse = {
    channel?: string;
    message?: string;
};

export type main_ChannelUpdate = {
    content?: string;
    id?: string;
};

export type main_CreateChannelInput = {
    consenters?: Array<main_AddressWithCerts>;
    name?: string;
    ordererOrgs?: Array<main_Organization>;
    peerOrgs?: Array<main_Organization>;
};

export type main_DecodeBlockInput = {
    dataB64?: string;
};

export type main_DecodeBlockResponse = {
    data?: {
        [key: string]: unknown;
    };
};

export type main_HostPort = {
    host?: string;
    port?: number;
};

export type main_Organization = {
    anchorPeers?: Array<main_HostPort>;
    name?: string;
    ordererEndpoints?: Array<(string)>;
    signCACert?: string;
    tlsCACert?: string;
};

export type main_Response = {
    [key: string]: unknown;
};

export type main_SetAnchorPeersInput = {
    anchorPeers?: Array<main_HostPort>;
    blockB64?: string;
    channelName?: string;
    mspID?: string;
};

export type main_SetAnchorPeersResponse = {
    blockB64?: string;
    noChanges?: boolean;
};

export type PostApiBlockAnchorpeersData = {
    /**
     * Anchor Peers Info
     */
    update: main_SetAnchorPeersInput;
};

export type PostApiBlockAnchorpeersResponse = main_SetAnchorPeersResponse;

export type PostApiBlockDecodeData = {
    /**
     * Block Data
     */
    block: main_DecodeBlockInput;
};

export type PostApiBlockDecodeResponse = main_DecodeBlockResponse;

export type PostApiChannelGenesisData = {
    /**
     * Channel Genesis Info
     */
    channel: main_CreateChannelInput;
};

export type PostApiChannelGenesisResponse = main_ChannelGenesisResponse;

export type PostApiChannelUpdateData = {
    /**
     * Channel Update Info
     */
    update: main_ChannelUpdate;
};

export type PostApiChannelUpdateResponse = main_Response;

export type $OpenApiTs = {
    '/api/block/anchorpeers': {
        post: {
            req: PostApiBlockAnchorpeersData;
            res: {
                /**
                 * OK
                 */
                200: main_SetAnchorPeersResponse;
            };
        };
    };
    '/api/block/decode': {
        post: {
            req: PostApiBlockDecodeData;
            res: {
                /**
                 * OK
                 */
                200: main_DecodeBlockResponse;
            };
        };
    };
    '/api/channel/genesis': {
        post: {
            req: PostApiChannelGenesisData;
            res: {
                /**
                 * Created
                 */
                201: main_ChannelGenesisResponse;
            };
        };
    };
    '/api/channel/update': {
        post: {
            req: PostApiChannelUpdateData;
            res: {
                /**
                 * Created
                 */
                201: main_Response;
                /**
                 * Bad Request
                 */
                400: main_Response;
            };
        };
    };
};