projects:
  fabriclaunch-api:
    # schema: http://localhost:3000/api/graphql
    schema: https://fabriclaunch.com/api/graphql
    documents: ./src/graphql/operations/**/*.graphql
    extensions:
      endpoints:
        default:
          # url: http://localhost:3000/api/graphql
          url: https://fabriclaunch.com/api/graphql
